/**
 * Cold-vs-warm cache benchmark for `routes.analyze` (T3.5) — the report's
 * headline optimisation (PROJECT-SPEC.md §9, PRD NFR-P3).
 *
 * Cold: clear the elevationCache collection, then analyze (every point a miss,
 * bounded by the provider's ~1 req/s rate limit). Warm: re-run N times against
 * the now-populated cache (zero provider calls) and report p50/p95 + hit ratio.
 *
 * MANUAL script — not part of `pnpm test`. Requires a running DB and network:
 *   pnpm db:start && pnpm -F server bench:analyze
 */
import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

import { createDefaultElevationService } from "@trek-together/api/integrations/elevation/default-service";
import { analyzeRoute } from "@trek-together/api/services/analyze";
import prisma from "@trek-together/db";

const WARM_RUNS = 10;
const SPACING_M = 60;

// A representative real route: a ridge line in Shenandoah NP (Old Rag area, VA).
// Coordinates are within SRTM bounds, so the profile is real terrain.
const ROUTE = [
  { lat: 38.5711, lng: -78.2942 },
  { lat: 38.5698, lng: -78.2921 },
  { lat: 38.5679, lng: -78.2907 },
  { lat: 38.5661, lng: -78.2896 },
  { lat: 38.5643, lng: -78.2889 },
  { lat: 38.5624, lng: -78.2884 },
  { lat: 38.5606, lng: -78.2881 },
  { lat: 38.5588, lng: -78.2878 },
  { lat: 38.5569, lng: -78.2876 },
  { lat: 38.5551, lng: -78.2875 },
  { lat: 38.5538, lng: -78.2876 },
  { lat: 38.5525, lng: -78.2878 },
];

function percentile(sorted: number[], p: number): number {
  const idx = Math.min(sorted.length - 1, Math.ceil((p / 100) * sorted.length) - 1);
  return sorted[Math.max(0, idx)] ?? 0;
}

function ratio(meta: { cacheHits: number; cacheMisses: number } | undefined): number {
  const m = meta ?? { cacheHits: 0, cacheMisses: 0 };
  const total = m.cacheHits + m.cacheMisses;
  return total === 0 ? 0 : m.cacheHits / total;
}

async function main() {
  const client = createDefaultElevationService({ db: prisma, requestId: "bench" });

  // --- Cold run: empty cache ---
  await prisma.elevationCache.deleteMany({});
  const coldStart = performance.now();
  const cold = await analyzeRoute(ROUTE, client, { spacingM: SPACING_M });
  const coldMs = performance.now() - coldStart;

  // --- Warm runs: cache fully populated ---
  const warmMs: number[] = [];
  let lastWarm = cold;
  for (let i = 0; i < WARM_RUNS; i++) {
    const t = performance.now();
    lastWarm = await analyzeRoute(ROUTE, client, { spacingM: SPACING_M });
    warmMs.push(performance.now() - t);
  }
  const sorted = [...warmMs].sort((a, b) => a - b);
  const warmP50 = percentile(sorted, 50);
  const warmP95 = percentile(sorted, 95);
  const uniquePoints = (cold.meta?.cacheHits ?? 0) + (cold.meta?.cacheMisses ?? 0);
  const speedup = coldMs / warmP50;

  const fmt = (n: number) => n.toFixed(1);
  console.log(`\nroutes.analyze cold-vs-warm cache benchmark`);
  console.log(`  route points (unique cache keys): ${uniquePoints}`);
  console.log(`  cold  (empty cache):  ${fmt(coldMs)} ms  (${cold.meta?.cacheMisses ?? 0} misses)`);
  console.log(`  warm  p50:            ${fmt(warmP50)} ms`);
  console.log(`  warm  p95:            ${fmt(warmP95)} ms`);
  console.log(`  warm  hit ratio:      ${(ratio(lastWarm.meta) * 100).toFixed(1)} %`);
  console.log(`  speed-up (cold/p50):  ${speedup.toFixed(0)}×\n`);

  const doc = `# Cache benchmark — routes.analyze (cold vs. warm)

> Auto-generated by \`apps/server/scripts/bench-analyze.ts\` (T3.5). Re-run with
> \`pnpm db:start && pnpm -F server bench:analyze\`.

**Run:** ${new Date().toISOString()} · provider \`${process.env.ELEVATION_PROVIDER ?? "opentopodata"}\` · Node ${process.version}

## Method

A representative Shenandoah ridge route (${ROUTE.length} vertices, densified to ${uniquePoints} unique
cache keys at ${SPACING_M} m spacing) is analyzed twice: **cold** after clearing the \`elevationCache\`
collection (every point a provider fetch, rate-limited to ~1 req/s), then **warm** ${WARM_RUNS}× against
the populated cache (zero provider calls). Cold is a single figure (bounded by the upstream API); warm is
summarised as p50/p95.

## Results

| Scenario | Latency | Cache |
|---|---|---|
| Cold (empty cache) | ${fmt(coldMs)} ms | ${cold.meta?.cacheMisses ?? 0} misses / 0 hits |
| Warm p50 | ${fmt(warmP50)} ms | ${(ratio(lastWarm.meta) * 100).toFixed(0)} % hit ratio |
| Warm p95 | ${fmt(warmP95)} ms | — |

**Warm cache is ~${speedup.toFixed(0)}× faster than cold**, with a ~${(ratio(lastWarm.meta) * 100).toFixed(0)} % hit ratio — the
cache converts a rate-limited multi-second cold analysis into a sub-millisecond-per-point warm one.

## Notes

- Cold latency is dominated by the provider's ≤1 req/s rate limit × number of batches (≤100 pts/batch),
  so it scales with route length, not CPU.
- Numbers vary with machine, network, and provider load; re-run to refresh this file.
`;

  const outPath = fileURLToPath(new URL("../../../docs/benchmarks/cache.md", import.meta.url));
  await mkdir(fileURLToPath(new URL("../../../docs/benchmarks/", import.meta.url)), {
    recursive: true,
  });
  await writeFile(outPath, doc, "utf8");
  console.log(`wrote ${outPath}\n`);
}

main()
  .then(() => prisma.$disconnect())
  .then(() => process.exit(0))
  .catch(async (err) => {
    console.error("bench-analyze failed:", err);
    await prisma.$disconnect();
    process.exit(1);
  });
